wpdb:
  image: mariadb
  ports:
    - "8081:3306"
  environment:
    MYSQL_ROOT_PASSWORD: root

phpmyadmin:
  image: phpmyadmin/phpmyadmin:latest
  ports:
    - "9090:80"
  links:
    - wpdb:db
  environment:
    MYSQL_USERNAME: root
    MYSQL_ROOT_PASSWORD: root

wp: 
  image: wordpress
  volumes:
    - ./site/:/var/www/html
  ports:
    - "8080:80"
  links: 
    - wpdb:mysql
  environment: 
    WORDPRESS_DB_NAME: wordpress

  